-- Generated by scripts/generate-emdash-core-migration.mjs
-- Do not edit manually. Regenerate when the pinned emdash package changes.
CREATE TABLE IF NOT EXISTS "_emdash_404_log" ("id" text primary key, "path" text not null, "referrer" text, "user_agent" text, "ip" text, "created_at" text default (datetime('now')), "hits" integer default 1 not null, "last_seen_at" text);
CREATE TABLE IF NOT EXISTS "_emdash_api_tokens" ("id" text primary key, "name" text not null, "token_hash" text not null unique, "prefix" text not null, "user_id" text not null, "scopes" text not null, "expires_at" text, "last_used_at" text, "created_at" text default (datetime('now')), constraint "api_tokens_user_fk" foreign key ("user_id") references "users" ("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "_emdash_authorization_codes" ("code_hash" text primary key, "client_id" text not null, "redirect_uri" text not null, "user_id" text not null, "scopes" text not null, "code_challenge" text not null, "code_challenge_method" text default 'S256' not null, "resource" text, "expires_at" text not null, "created_at" text default (datetime('now')), constraint "auth_codes_user_fk" foreign key ("user_id") references "users" ("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "_emdash_bylines" ("id" text primary key, "slug" text not null unique, "display_name" text not null, "bio" text, "avatar_media_id" text references "media" ("id") on delete set null, "website_url" text, "user_id" text references "users" ("id") on delete set null, "is_guest" integer default 0 not null, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')));
CREATE TABLE IF NOT EXISTS "_emdash_collections" ("id" text primary key, "slug" text not null unique, "label" text not null, "label_singular" text, "description" text, "icon" text, "supports" text, "source" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "search_config" text, has_seo INTEGER NOT NULL DEFAULT 0, url_pattern TEXT, "comments_enabled" integer default 0, "comments_moderation" text default 'first_time', "comments_closed_after_days" integer default 90, "comments_auto_approve_users" integer default 1);
CREATE TABLE IF NOT EXISTS "_emdash_comments" ("id" text primary key, "collection" text not null, "content_id" text not null, "parent_id" text references "_emdash_comments" ("id") on delete cascade, "author_name" text not null, "author_email" text not null, "author_user_id" text references "users" ("id") on delete set null, "body" text not null, "status" text default 'pending' not null, "ip_hash" text, "user_agent" text, "moderation_metadata" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')));
CREATE TABLE IF NOT EXISTS "_emdash_content_bylines" ("id" text primary key, "collection_slug" text not null, "content_id" text not null, "byline_id" text not null references "_emdash_bylines" ("id") on delete cascade, "sort_order" integer default 0 not null, "role_label" text, "created_at" text default (datetime('now')), constraint "content_bylines_unique" unique ("collection_slug", "content_id", "byline_id"));
CREATE TABLE IF NOT EXISTS "_emdash_cron_tasks" ("id" text primary key, "plugin_id" text not null, "task_name" text not null, "schedule" text not null, "is_oneshot" integer default 0 not null, "data" text, "next_run_at" text not null, "last_run_at" text, "status" text default 'idle' not null, "locked_at" text, "enabled" integer default 1 not null, "created_at" text default (datetime('now')), constraint "uq_cron_tasks_plugin_task" unique ("plugin_id", "task_name"));
CREATE TABLE IF NOT EXISTS "_emdash_device_codes" ("device_code" text primary key, "user_code" text not null unique, "scopes" text not null, "user_id" text, "status" text default 'pending' not null, "expires_at" text not null, "interval" integer default 5 not null, "created_at" text default (datetime('now')), "last_polled_at" text);
CREATE TABLE IF NOT EXISTS "_emdash_fields" ("id" text primary key, "collection_id" text not null, "slug" text not null, "label" text not null, "type" text not null, "column_type" text not null, "required" integer default 0, "unique" integer default 0, "default_value" text, "validation" text, "widget" text, "options" text, "sort_order" integer default 0, "created_at" text default (datetime('now')), "searchable" integer default 0, translatable INTEGER NOT NULL DEFAULT 1, constraint "fields_collection_fk" foreign key ("collection_id") references "_emdash_collections" ("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "_emdash_menu_items" ("id" text primary key, "menu_id" text not null, "parent_id" text, "sort_order" integer default 0 not null, "type" text not null, "reference_collection" text, "reference_id" text, "custom_url" text, "label" text not null, "title_attr" text, "target" text, "css_classes" text, "created_at" text default (datetime('now')), "locale" text default 'en' not null, "translation_group" text);
CREATE TABLE IF NOT EXISTS "_emdash_menus" ("id" text primary key, "name" text not null, "label" text not null, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "locale" text default 'en' not null, "translation_group" text, constraint "_emdash_menus_name_locale_unique" unique ("name", "locale"));
CREATE TABLE IF NOT EXISTS "_emdash_migrations" ("name" varchar(255) not null primary key, "timestamp" varchar(255) not null);
CREATE TABLE IF NOT EXISTS "_emdash_migrations_lock" ("id" varchar(255) not null primary key, "is_locked" integer default 0 not null);
CREATE TABLE IF NOT EXISTS "_emdash_oauth_clients" ("id" text primary key, "name" text not null, "redirect_uris" text not null, "scopes" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')));
CREATE TABLE IF NOT EXISTS "_emdash_oauth_tokens" ("token_hash" text primary key, "token_type" text not null, "user_id" text not null, "scopes" text not null, "client_type" text default 'cli' not null, "expires_at" text not null, "refresh_token_hash" text, "created_at" text default (datetime('now')), client_id TEXT, constraint "oauth_tokens_user_fk" foreign key ("user_id") references "users" ("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "_emdash_rate_limits" ("key" text not null, "window" text not null, "count" integer default 1 not null, constraint "pk_rate_limits" primary key ("key", "window"));
CREATE TABLE IF NOT EXISTS "_emdash_redirects" ("id" text primary key, "source" text not null, "destination" text not null, "type" integer default 301 not null, "is_pattern" integer default 0 not null, "enabled" integer default 1 not null, "hits" integer default 0 not null, "last_hit_at" text, "group_name" text, "auto" integer default 0 not null, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')));
CREATE TABLE IF NOT EXISTS "_emdash_sections" ("id" text primary key, "slug" text not null unique, "title" text not null, "description" text, "keywords" text, "content" text not null, "preview_media_id" text, "source" text default 'user' not null, "theme_id" text, "created_at" text default CURRENT_TIMESTAMP, "updated_at" text default CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "_emdash_seo" ("collection" text not null, "content_id" text not null, "seo_title" text, "seo_description" text, "seo_image" text, "seo_canonical" text, "seo_no_index" integer default 0 not null, "created_at" text default (datetime('now')) not null, "updated_at" text default (datetime('now')) not null, constraint "_emdash_seo_pk" primary key ("collection", "content_id"));
CREATE TABLE IF NOT EXISTS "_emdash_taxonomy_defs" ("id" text primary key, "name" text not null, "label" text not null, "label_singular" text, "hierarchical" integer default 0, "collections" text, "created_at" text default (datetime('now')), "locale" text default 'en' not null, "translation_group" text, constraint "_emdash_taxonomy_defs_name_locale_unique" unique ("name", "locale"));
CREATE TABLE IF NOT EXISTS "_emdash_widget_areas" ("id" text primary key, "name" text not null unique, "label" text not null, "description" text, "created_at" text default CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "_emdash_widgets" ("id" text primary key, "area_id" text not null references "_emdash_widget_areas" ("id") on delete cascade, "sort_order" integer default 0 not null, "type" text not null, "title" text, "content" text, "menu_name" text, "component_id" text, "component_props" text, "created_at" text default CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "_plugin_indexes" ("plugin_id" text not null, "collection" text not null, "index_name" text not null, "fields" text not null, "created_at" text default (datetime('now')), constraint "pk_plugin_indexes" primary key ("plugin_id", "collection", "index_name"));
CREATE TABLE IF NOT EXISTS "_plugin_state" ("plugin_id" text primary key, "version" text not null, "status" text default 'installed' not null, "installed_at" text default (datetime('now')), "activated_at" text, "deactivated_at" text, "data" text, source TEXT NOT NULL DEFAULT 'config', marketplace_version TEXT, display_name TEXT, description TEXT, registry_publisher_did TEXT, registry_slug TEXT);
CREATE TABLE IF NOT EXISTS "_plugin_storage" ("plugin_id" text not null, "collection" text not null, "id" text not null, "data" text not null, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), constraint "pk_plugin_storage" primary key ("plugin_id", "collection", "id"));
CREATE TABLE IF NOT EXISTS "allowed_domains" ("domain" text primary key, "default_role" integer default 20 not null, "enabled" integer default 1 not null, "created_at" text default (datetime('now')));
CREATE TABLE IF NOT EXISTS "audit_logs" ("id" text primary key, "timestamp" text default (datetime('now')), "actor_id" text, "actor_ip" text, "action" text not null, "resource_type" text, "resource_id" text, "details" text, "status" text);
CREATE TABLE IF NOT EXISTS "auth_challenges" ("challenge" text primary key, "type" text not null, "user_id" text, "data" text, "expires_at" text not null, "created_at" text default (datetime('now')));
CREATE TABLE IF NOT EXISTS "auth_tokens" ("hash" text primary key, "user_id" text, "email" text, "type" text not null, "role" integer, "invited_by" text, "expires_at" text not null, "created_at" text default (datetime('now')), constraint "auth_tokens_user_fk" foreign key ("user_id") references "users" ("id") on delete cascade, constraint "auth_tokens_invited_by_fk" foreign key ("invited_by") references "users" ("id") on delete set null);
CREATE TABLE IF NOT EXISTS "content_taxonomies" ("collection" text not null, "entry_id" text not null, "taxonomy_id" text not null, constraint "content_taxonomies_pk" primary key ("collection", "entry_id", "taxonomy_id"));
CREATE TABLE IF NOT EXISTS "credentials" ("id" text primary key, "user_id" text not null, "public_key" blob not null, "counter" integer default 0 not null, "device_type" text not null, "backed_up" integer default 0 not null, "transports" text, "name" text, "created_at" text default (datetime('now')), "last_used_at" text default (datetime('now')), "algorithm" integer default -7 not null, constraint "credentials_user_fk" foreign key ("user_id") references "users" ("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "media" ("id" text primary key, "filename" text not null, "mime_type" text not null, "size" integer, "width" integer, "height" integer, "alt" text, "caption" text, "storage_key" text not null, "content_hash" text, "created_at" text default (datetime('now')), "author_id" text, "status" text default 'ready' not null, blurhash TEXT, dominant_color TEXT);
CREATE TABLE IF NOT EXISTS "oauth_accounts" ("provider" text not null, "provider_account_id" text not null, "user_id" text not null, "created_at" text default (datetime('now')), constraint "oauth_accounts_pk" primary key ("provider", "provider_account_id"), constraint "oauth_accounts_user_fk" foreign key ("user_id") references "users" ("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "options" ("name" text primary key, "value" text not null);
CREATE TABLE IF NOT EXISTS "revisions" ("id" text primary key, "collection" text not null, "entry_id" text not null, "data" text not null, "author_id" text, "created_at" text default (datetime('now')));
CREATE TABLE IF NOT EXISTS "taxonomies" ("id" text primary key, "name" text not null, "slug" text not null, "label" text not null, "parent_id" text, "data" text, "locale" text default 'en' not null, "translation_group" text, constraint "taxonomies_name_slug_locale_unique" unique ("name", "slug", "locale"), constraint "taxonomies_parent_fk" foreign key ("parent_id") references "taxonomies" ("id") on delete set null);
CREATE TABLE IF NOT EXISTS "users" ("id" text primary key, "email" text not null unique, "name" text, "avatar_url" text, "role" integer default 10 not null, "email_verified" integer default 0 not null, "data" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), disabled INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS "idx_404_log_created" on "_emdash_404_log" ("created_at");
CREATE INDEX IF NOT EXISTS "idx_404_log_last_seen" on "_emdash_404_log" ("last_seen_at");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_404_log_path_unique" on "_emdash_404_log" ("path");
CREATE INDEX IF NOT EXISTS "idx__emdash_menu_items_locale" on "_emdash_menu_items" ("locale");
CREATE INDEX IF NOT EXISTS "idx__emdash_menu_items_translation_group" on "_emdash_menu_items" ("translation_group");
CREATE INDEX IF NOT EXISTS "idx__emdash_menus_locale" on "_emdash_menus" ("locale");
CREATE INDEX IF NOT EXISTS "idx__emdash_menus_translation_group" on "_emdash_menus" ("translation_group");
CREATE INDEX IF NOT EXISTS "idx__emdash_taxonomy_defs_locale" on "_emdash_taxonomy_defs" ("locale");
CREATE INDEX IF NOT EXISTS "idx__emdash_taxonomy_defs_translation_group" on "_emdash_taxonomy_defs" ("translation_group");
CREATE INDEX IF NOT EXISTS "idx_api_tokens_token_hash" on "_emdash_api_tokens" ("token_hash");
CREATE INDEX IF NOT EXISTS "idx_api_tokens_user_id" on "_emdash_api_tokens" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_audit_action" on "audit_logs" ("action");
CREATE INDEX IF NOT EXISTS "idx_audit_actor" on "audit_logs" ("actor_id");
CREATE INDEX IF NOT EXISTS "idx_audit_resource" on "audit_logs" ("resource_type", "resource_id");
CREATE INDEX IF NOT EXISTS "idx_audit_timestamp" on "audit_logs" ("timestamp");
CREATE INDEX IF NOT EXISTS "idx_auth_challenges_expires" on "auth_challenges" ("expires_at");
CREATE INDEX IF NOT EXISTS "idx_auth_codes_expires" on "_emdash_authorization_codes" ("expires_at");
CREATE INDEX IF NOT EXISTS "idx_auth_tokens_email" on "auth_tokens" ("email");
CREATE INDEX IF NOT EXISTS "idx_bylines_display_name" on "_emdash_bylines" ("display_name");
CREATE INDEX IF NOT EXISTS "idx_bylines_slug" on "_emdash_bylines" ("slug");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_bylines_user_id_unique"
		ON "_emdash_bylines" (user_id)
		WHERE user_id IS NOT NULL
	;
CREATE INDEX IF NOT EXISTS idx_comments_approved
		ON _emdash_comments (id)
		WHERE status = 'approved'
	;
CREATE INDEX IF NOT EXISTS "idx_comments_author_email" on "_emdash_comments" ("author_email");
CREATE INDEX IF NOT EXISTS "idx_comments_author_user" on "_emdash_comments" ("author_user_id");
CREATE INDEX IF NOT EXISTS "idx_comments_content" on "_emdash_comments" ("collection", "content_id", "status");
CREATE INDEX IF NOT EXISTS "idx_comments_parent" on "_emdash_comments" ("parent_id");
CREATE INDEX IF NOT EXISTS idx_comments_pending
		ON _emdash_comments (id)
		WHERE status = 'pending'
	;
CREATE INDEX IF NOT EXISTS idx_comments_spam
		ON _emdash_comments (id)
		WHERE status = 'spam'
	;
CREATE INDEX IF NOT EXISTS "idx_comments_status" on "_emdash_comments" ("status", "created_at");
CREATE INDEX IF NOT EXISTS idx_comments_trash
		ON _emdash_comments (id)
		WHERE status = 'trash'
	;
CREATE INDEX IF NOT EXISTS "idx_content_bylines_byline" on "_emdash_content_bylines" ("byline_id");
CREATE INDEX IF NOT EXISTS "idx_content_bylines_content" on "_emdash_content_bylines" ("collection_slug", "content_id", "sort_order");
CREATE INDEX IF NOT EXISTS idx_content_taxonomies_term ON content_taxonomies(taxonomy_id);
CREATE INDEX IF NOT EXISTS "idx_credentials_user" on "credentials" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_cron_tasks_due" on "_emdash_cron_tasks" ("enabled", "status", "next_run_at");
CREATE INDEX IF NOT EXISTS "idx_cron_tasks_plugin" on "_emdash_cron_tasks" ("plugin_id");
CREATE INDEX IF NOT EXISTS idx_emdash_seo_collection
		ON _emdash_seo (collection)
	;
CREATE INDEX IF NOT EXISTS "idx_fields_collection" on "_emdash_fields" ("collection_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_fields_collection_slug" on "_emdash_fields" ("collection_id", "slug");
CREATE INDEX IF NOT EXISTS "idx_fields_sort" on "_emdash_fields" ("collection_id", "sort_order");
CREATE INDEX IF NOT EXISTS "idx_media_content_hash" on "media" ("content_hash");
CREATE INDEX IF NOT EXISTS "idx_media_created_at" on "media" ("created_at");
CREATE INDEX IF NOT EXISTS "idx_media_filename" on "media" ("filename");
CREATE INDEX IF NOT EXISTS "idx_media_mime_type" on "media" ("mime_type");
CREATE INDEX IF NOT EXISTS "idx_media_status" on "media" ("status");
CREATE INDEX IF NOT EXISTS "idx_menu_items_menu" on "_emdash_menu_items" ("menu_id", "sort_order");
CREATE INDEX IF NOT EXISTS "idx_menu_items_parent" on "_emdash_menu_items" ("parent_id");
CREATE INDEX IF NOT EXISTS "idx_oauth_accounts_user" on "oauth_accounts" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_oauth_tokens_expires" on "_emdash_oauth_tokens" ("expires_at");
CREATE INDEX IF NOT EXISTS "idx_oauth_tokens_user_id" on "_emdash_oauth_tokens" ("user_id");
CREATE INDEX IF NOT EXISTS idx_plugin_state_registry
			ON _plugin_state (source)
			WHERE source = 'registry'
		;
CREATE INDEX IF NOT EXISTS idx_plugin_state_source
		ON _plugin_state (source)
		WHERE source = 'marketplace'
	;
CREATE INDEX IF NOT EXISTS "idx_plugin_storage_list" on "_plugin_storage" ("plugin_id", "collection", "created_at");
CREATE INDEX IF NOT EXISTS "idx_rate_limits_window" on "_emdash_rate_limits" ("window");
CREATE INDEX IF NOT EXISTS "idx_redirects_enabled" on "_emdash_redirects" ("enabled");
CREATE INDEX IF NOT EXISTS "idx_redirects_group" on "_emdash_redirects" ("group_name");
CREATE INDEX IF NOT EXISTS "idx_redirects_source" on "_emdash_redirects" ("source");
CREATE INDEX IF NOT EXISTS "idx_revisions_entry" on "revisions" ("collection", "entry_id");
CREATE INDEX IF NOT EXISTS "idx_sections_source" on "_emdash_sections" ("source");
CREATE INDEX IF NOT EXISTS "idx_taxonomies_locale" on "taxonomies" ("locale");
CREATE INDEX IF NOT EXISTS "idx_taxonomies_name" on "taxonomies" ("name");
CREATE INDEX IF NOT EXISTS "idx_taxonomies_translation_group" on "taxonomies" ("translation_group");
CREATE INDEX IF NOT EXISTS "idx_users_disabled" on "users" ("disabled");
CREATE INDEX IF NOT EXISTS "idx_users_email" on "users" ("email");
CREATE INDEX IF NOT EXISTS "idx_widgets_area" on "_emdash_widgets" ("area_id", "sort_order");
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('001_initial', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('002_media_status', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('003_schema_registry', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('004_plugins', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('005_menus', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('006_taxonomy_defs', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('007_widgets', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('008_auth', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('009_user_disabled', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('011_sections', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('012_search', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('013_scheduled_publishing', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('014_draft_revisions', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('015_indexes', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('016_api_tokens', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('017_authorization_codes', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('018_seo', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('019_i18n', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('020_collection_url_pattern', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('021_remove_section_categories', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('022_marketplace_plugin_state', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('023_plugin_metadata', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('024_media_placeholders', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('025_oauth_clients', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('026_cron_tasks', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('027_comments', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('028_drop_author_url', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('029_redirects', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('030_widen_scheduled_index', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('031_bylines', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('032_rate_limits', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('033_optimize_content_indexes', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('034_published_at_index', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('035_bounded_404_log', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('036_i18n_menus_and_taxonomies', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('037_credential_algorithm', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('038_registry_plugin_state', '1970-01-01T00:00:00.000Z');
INSERT OR IGNORE INTO "_emdash_migrations" ("name", "timestamp") VALUES ('039_fix_fts5_triggers', '1970-01-01T00:00:00.000Z');
